name: Docker Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        # This command tries to find the Dockerfile regardless of the folder name
        DOCKER_PATH=$(find . -name "Dockerfile" | head -n 1)
        docker build . --file $DOCKER_PATH -t my-app:latest

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./task-3/aiswaryasnair-2@mulearn/
